#!/bin/bash
# SessionStart Hook - Auto-configure DSA Stack environment
#
# Purpose: Initialize environment variables and PATH on session start.
# Behavior: Non-blocking (exit 0 always) - logs errors but continues.
#
# Integration: Sources env/dsa-stack.sh generated by `make env` and
# persists environment by adding source command to CLAUDE_ENV_FILE.

# Only configure if CLAUDE_ENV_FILE is available (SessionStart only)
if [ -n "$CLAUDE_ENV_FILE" ]; then
  ENV_SCRIPT="$CLAUDE_PROJECT_DIR/env/dsa-stack.sh"

  if [ -f "$ENV_SCRIPT" ]; then
    # Add source command to CLAUDE_ENV_FILE (portable across sh/bash/zsh)
    printf '. "%s"\n' "$ENV_SCRIPT" >> "$CLAUDE_ENV_FILE"
    echo "DSA Stack session initialized using env/dsa-stack.sh" >&2
  else
    # Fallback: env script not generated yet (user needs to run `make env`)
    echo "Warning: env/dsa-stack.sh not found. Run 'make env' to generate environment setup." >&2
    echo "Falling back to basic PATH addition." >&2

    # Minimal fallback using absolute path (prepend for priority)
    printf 'export PATH="%s/build/bin:$PATH"\n' "$CLAUDE_PROJECT_DIR" >> "$CLAUDE_ENV_FILE"
  fi
else
  echo "Warning: CLAUDE_ENV_FILE not set, skipping environment setup" >&2
fi

# Always exit 0 (non-blocking behavior)
exit 0
