# Default target
.PHONY: test test-shells help setup pre-commit

test:
	./tests/test-all.sh

test-shells:
	TEST_SHELLS="bash zsh" ./tests/test-all.sh

pre-commit:
	HOOKS_DIR=$$(git rev-parse --git-path hooks 2>/dev/null || echo ".git/hooks"); \
	mkdir -p "$$HOOKS_DIR"; \
	ln -sf ../../scripts/pre-commit "$$HOOKS_DIR/pre-commit"; \
	echo "✓ Pre-commit hook installed"; \

setup:
	@echo "Generating local setup script..."
	@echo '#!/bin/bash' > setup.sh
	@echo '' >> setup.sh
	@echo '# Auto-generated by make setup' >> setup.sh
	@echo '# This file is local-only and gitignored' >> setup.sh
	@echo '' >> setup.sh
	@echo 'export AGENTIZE_HOME="$(CURDIR)"' >> setup.sh
	@echo 'source "$$AGENTIZE_HOME/scripts/wt-cli.sh"' >> setup.sh
	@echo 'source "$$AGENTIZE_HOME/scripts/lol-cli.sh"' >> setup.sh
	@chmod +x setup.sh
	@echo ""
	@echo "✓ Created setup.sh in repository root"
	@echo ""
	@echo "Usage:"
	@echo "  1. Source it now:  source setup.sh"
	@echo "  2. For persistence, add to your shell RC file:"
	@echo "     cat setup.sh >> ~/.bashrc  # or ~/.zshrc"

help:
	@echo "Available targets:"
	@echo "  make test                - Run all tests (bash only)"
	@echo "  make test-shells         - Run all tests under multiple shells (bash and zsh)"
	@echo "  make setup               - Generate local setup.sh for development"
	@echo ""
	@echo "SDK usage:"
	@echo "  lol init --name your_project --lang c --path /path/to/project"
	@echo "  lol update                # From project directory"
	@echo "  lol --help                # For all options"
