#!/usr/bin/env bash
# Test: Makefile setup target generates zsh completion snippet in setup.sh

# Shared test helpers
set -e
TESTS_COMMON="${AGENTIZE_TESTS_COMMON:-$(git rev-parse --show-toplevel 2>/dev/null)/tests/common.sh}"
[ -f "$TESTS_COMMON" ] || { echo "Error: Cannot locate tests/common.sh" >&2; exit 1; }
source "$TESTS_COMMON"

test_info "Makefile setup target generates zsh completion snippet"

# Create temporary directory for test
TMP_DIR=$(make_temp_dir "test-makefile-zsh-completion")
trap "cleanup_dir '$TMP_DIR'" EXIT

# Run make setup in a subshell to capture generated setup.sh
cd "$PROJECT_ROOT"
make setup > /dev/null 2>&1

# Verify setup.sh was created
if [ ! -f "$PROJECT_ROOT/setup.sh" ]; then
  test_fail "setup.sh not generated by make setup"
fi

# Verify zsh completion block is present
if ! grep -q "if.*zsh" "$PROJECT_ROOT/setup.sh"; then
  test_fail "setup.sh missing zsh conditional block"
fi

# Verify fpath update is present
if ! grep -q "fpath.*completion" "$PROJECT_ROOT/setup.sh"; then
  test_fail "setup.sh missing fpath update for completion"
fi

# Verify compinit is mentioned (either check or invocation)
if ! grep -q "compinit" "$PROJECT_ROOT/setup.sh"; then
  test_fail "setup.sh missing compinit reference"
fi

test_pass "Makefile generates setup.sh with zsh completion support"
