#!/usr/bin/env bash
# Test: Makefile setup target generates zsh completion snippet in setup.sh

# Shared test helpers
set -e
SCRIPT_PATH="$0"
if [ -n "${BASH_SOURCE[0]-}" ]; then
  SCRIPT_PATH="${BASH_SOURCE[0]}"
fi
if [ "${SCRIPT_PATH%/*}" = "$SCRIPT_PATH" ]; then
  SCRIPT_DIR="."
else
  SCRIPT_DIR="${SCRIPT_PATH%/*}"
fi
source "$SCRIPT_DIR/../common.sh"

test_info "Makefile setup target generates zsh completion snippet"

# Create temporary directory for test
TMP_DIR=$(make_temp_dir "test-makefile-zsh-completion")
trap "cleanup_dir '$TMP_DIR'" EXIT

# Run make setup in a subshell to capture generated setup.sh
cd "$PROJECT_ROOT"
make setup > /dev/null 2>&1

# Verify setup.sh was created
if [ ! -f "$PROJECT_ROOT/setup.sh" ]; then
  test_fail "setup.sh not generated by make setup"
fi

# Verify zsh completion block is present
if ! grep -q "if.*zsh" "$PROJECT_ROOT/setup.sh"; then
  test_fail "setup.sh missing zsh conditional block"
fi

# Verify fpath update is present
if ! grep -q "fpath.*completion" "$PROJECT_ROOT/setup.sh"; then
  test_fail "setup.sh missing fpath update for completion"
fi

# Verify compinit is mentioned (either check or invocation)
if ! grep -q "compinit" "$PROJECT_ROOT/setup.sh"; then
  test_fail "setup.sh missing compinit reference"
fi

test_pass "Makefile generates setup.sh with zsh completion support"
